name: GitRepoMirroring

on:
  - push
  - delete

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Mirroring
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: shashinma/git-repo-mirror@v1.0.0
      with:
        # Such as https://github.com/shashinma/git-repo-mirror.git
        target-url: ${{ secrets.GIT_URL }}
        # Such as shashinma
        target-username: ${{ secrets.GIT_USERNAME }}
          # You can store token in your project's 'Setting > Secrets' and reference the name here. Such as ${{ secrets.ACCESS\_TOKEN }}
        target-token: ${{ secrets.GIT_MIRROR_TOKEN }}
